### ISSUE TITLE
Feature: Quality Track selection

### ISSUE THREAD

**Issue by sudhanshugairola** [bcc-code/bccm-player#1]
Quality track selection is missing for hls and dash, hope you will add soon.

**Comment by andreasgangso** [comment]
Hi, thanks for the feedback.
I can add this. Is it a critical feature for you to have?

**Comment by sudhanshugairola** [comment]
That is critical for every one, by quality selection that help in stream video in other available resolutions for hls or dash content, so that is save more internet data for every user.

**Comment by sudhanshugairola** [comment]
May be you will soon add more features for Android and iOS like.
(By Exoplayer Android and AVplayer iOS)
1. Buffering configuration like (important like better_player)
2. Player complete dispose (critical).
3. Notification configuration (not much important)
4. Cache feature (which is not important, yes may be use by some users)

**Comment by andreasgangso** [comment]
> Buffering configuration like (important like better_player)

This is relatively simple to add. I described the process [here](https://github.com/bcc-code/bccm-player/issues/2), if you want to make a PR.

> Player complete dispose (critical).

You mean a way to dispose a player? True, I never noticed that this was missing because we never needed more than 1 persistent player.
Issue [here](https://github.com/bcc-code/bccm-player/issues/3).
