### ISSUE TITLE
Custom rendering of subtitles

### ISSUE THREAD

**Issue by sudhanshugairola** [bcc-code/bccm-player#15]
some time user zoom in and out or pinch to far zoom then subtitle hide by nativeview side, if render subtitle available the solve that issue for most of users and set render subtitle text over on their UI.

That's why you will find another plugins for subtitles https://pub.dev/packages/subtitle_wrapper_package like this.
It's better if you provide render subtitles in text that will help to many user to avoid that out region subtitles display.

**Comment by andreasgangso** [comment]
The subtitle_wrapper_package exists because video_player doesnt have subtitles. But bccm_player does have subtitles.

There's a slight language barrier here which makes it hard for me to understand what the actual issue here is though :/
But I'll try:
Do you mean that if you zoom in on the player, the subtitles would disappear because they are too far down?
If so, would it solve the use case if you simply had more control over where the subtitles are positioned?
`controller.setSubtitleSettings(offsetY: -100);`

If I haven't understood what you mean: Can you provide a more detailed explanation? It could help with screenshots/illustrations of what you mean, and reproduction steps (1, 2, 3 numbered list)

**Comment by sudhanshugairola** [comment]
yes Render subtitle text is necessary for customization like change colors, size, background transparent, for adjusting position of subtitle. i'm testing all videoplayer plugins that why i tell you important and advanced things for improving quality of bcc_player plugin

**Comment by sudhanshugairola** [comment]
![Uploading Screenshot_20230821_213801.jpg…]()

**Comment by sudhanshugairola** [comment]
![Screenshot_20230821_213801](https://github.com/bcc-code/bccm-player/assets/42227576/04079ac9-77f2-4683-b27c-a6ff13f6056c)

**Comment by sudhanshugairola** [comment]
Atleast add controller.setSubtitleSettings(offsetY: -100) and change background color to transparent

**Comment by sudhanshugairola** [comment]
That come while zoom the vudeo

**Comment by andreasgangso** [comment]
Ah, it was while zooming. Remember to include all important details like that.
Also, please keep your comments in 1. The best is to think through what you want to say before clicking "send".
