### ISSUE TITLE
|BUG| Same name tracks show only one

### ISSUE THREAD

**Issue by sudhanshugairola** [bcc-code/bccm-player#17]
There is a bug in track list if there is two same name audio or subtitles or in quality like 2x1080p it shows only one from list and second one hide somewhere.

**Comment by sudhanshugairola** [comment]
/

**Comment by sudhanshugairola** [comment]
Any update on this issue

**Comment by andreasgangso** [comment]
Hi @sudhanshugairola this was kind of intentional, as most users aren't technical enough to understand the difference between two streams with the same resolution. See e.g. youtube.

If you want to do something custom, you may want to write your own controls.
And with v1.0.0, you can, without losing fullscreening.
See https://bcc-code.github.io/bccm-player/advanced-usage/custom-controls/

**Comment by sudhanshugairola** [comment]
You are right but some time same resolution contain different codec like some resolution are HDR 1080 and SDR 1080 then this is unfair  to quality selection

**Comment by andreasgangso** [comment]
@sudhanshugairola I am aware, but I don't think it belongs in the default controls. You are free to make your own UI for this.

**Comment by andreasgangso** [comment]
Showing absolutely all tracks could be made into an option, though.
I'm don't think I'm going to implement it, but I would be happy to review a PR if you want to.

**Comment by sudhanshugairola** [comment]
I know, but I'm also check externally by videoplayer controller still same bug that show only one track of two same name 1080p 1080p quality even both 1080p track has different bitrate of video resolutions.

**Comment by sudhanshugairola** [comment]
ok i got
