### ISSUE TITLE
Issue with HDR video brightness & Colors

### ISSUE THREAD

**Issue by sudhanshugairola** [bcc-code/bccm-player#5]
Platform Android:

There is something wrong with HDR video when i play HDR with is loss of brightness and colors fading or you can say that color burn.

Test 1080 quality that contain HDR content.

Something is notice in pip mode hdr work well as i come back inside app that fade color and loss brightness.

HDR urls: 

https://devstreaming-cdn.apple.com/videos/streaming/examples/adv_dv_atmos/main.m3u8

https://springstream.blob.core.windows.net/springstream/Hollywood/Hollywood%20Series/Wednesday/season%201/e1/master.m3u8

@andreasgangso.

**Comment by andreasgangso** [comment]
I'll have a look

**Comment by sudhanshugairola** [comment]
Great try to watch night scene

**Comment by andreasgangso** [comment]
I think I fixed it in #6 
Try updating to version 0.2.0+hdr.1 and confirm if it works before i merge

**Comment by sudhanshugairola** [comment]
Fixed great.

**Comment by andreasgangso** [comment]
@sudhanshugairola the reason I used texture_view is because of [this flutter bug with surface views](https://github.com/flutter/flutter/issues/89558).

1. Play a video in a stack with something in front
2. Leave to home screen (paused so it doesnt pip)
3. Open the app again, and it will pop to the top.

https://github.com/bcc-code/bccm-player/assets/727125/39747eb2-b552-4be5-8b5c-8c0138993d1b

So I will have to make surface_view and HDR content opt-in because of this.

**Comment by sudhanshugairola** [comment]
Got it

**Comment by sudhanshugairola** [comment]
May be one simple solution of this as someone press home button or app goes inactivity state like app in background then shift to textureview instead of surface view, as session of app resumed then move back or surface view
